--- 
abstract: Encoding and decoding of base36 strings
author: 
  - Rune Henssel <perl@henssel.dk>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Math-Base36
no_index: 
  directory: 
    - inc
    - t
requires: 
  Math::BigInt: 0
  perl: 5.6.0
version: 0.04
